// A stand-in for the Wails bridge, so the built page can be opened in a
// normal browser: every Go method the page calls is a promise here, and
// every call is appended to window.calls for the test to read. `emit`
// stands in for the `shown` event ("window.emit('links')").
window.calls = [];
window.favs = [];

// The runtime module generated by Wails implements EventsOn on top of
// EventsOnMultiple, so that is the one the page ends up calling. Both are
// provided so the bridge keeps working whichever the page uses. The last
// listener of each event is kept, so a test can fire `icons` too.
window.listeners = {};
window.runtime = {
    EventsOnMultiple: (name, callback) => {
        window.listeners[name] = callback;
        if (name === 'shown') {
            window.emit = callback;
        }
    },
    EventsOn: (name, callback) => {
        window.runtime.EventsOnMultiple(name, callback);
    },
};

// The fixture: two discovered apps (one an Edge app on github.com), one
// hand-added app, three links, two categories per tab.
const apps = [
    {id: 'mine', key: 'apps:mine', kind: 'app', source: 'library', name: 'Mine', description: 'A hand-added app', url: '', host: '', path: '/Applications/Mine.app', bundleId: '', category: 'tools', keywords: [], iconUrl: '', hidden: false, missing: false},
    {id: 'app-mail', key: 'apps:app-mail', kind: 'app', source: 'applications', name: 'Mail', description: '', url: '', host: '', path: '/Applications/Mail.app', bundleId: 'com.apple.mail', category: 'applications', keywords: [], iconUrl: '', hidden: false, missing: false},
    {id: 'edge-github', key: 'apps:edge-github', kind: 'app', source: 'edge', name: 'GitHub', description: 'github.com', url: '', host: 'github.com', path: '/Users/someone/Applications/Edge Apps.localized/GitHub.app', bundleId: '', category: 'edge', keywords: [], iconUrl: '', hidden: false, missing: false},
];

const links = [
    {id: 'mdn', key: 'links:mdn', kind: 'link', source: 'library', name: 'MDN', description: 'Web reference', url: 'https://developer.mozilla.org', host: 'developer.mozilla.org', path: '', bundleId: '', category: 'docs', keywords: [], iconUrl: '', hidden: false, missing: false},
    {id: 'gitea', key: 'links:gitea', kind: 'link', source: 'library', name: 'Gitea', description: 'Repos', url: 'https://repos.example.com', host: 'repos.example.com', path: '', bundleId: '', category: 'eco', keywords: ['git'], iconUrl: '', hidden: false, missing: false},
    {id: 'github', key: 'links:github', kind: 'link', source: 'library', name: 'GitHub', description: 'Pull requests', url: 'https://github.com', host: 'github.com', path: '', bundleId: '', category: 'eco', keywords: [], iconUrl: '', hidden: false, missing: false},
];

const call = (name) => async (...args) => {
    window.calls.push([name, ...args].join(':'));
};

window.go = {main: {App: {
    Items: async (tab) => (tab === 'links' ? links : apps),
    Categories: async (tab) => (tab === 'links'
        ? [{id: 'eco', name: 'Ecosystem', tab: 'links', virtual: false}, {id: 'docs', name: 'Docs', tab: 'links', virtual: false}]
        : [{id: 'tools', name: 'Tools', tab: 'apps', virtual: false}, {id: 'applications', name: '', tab: 'apps', virtual: true}, {id: 'edge', name: '', tab: 'apps', virtual: true}]),
    Usage: async () => ({opens: {'links:gitea': 2}, lastOpened: {'links:gitea': '2026-09-26T10:00:00Z'}, favorites: window.favs}),
    Settings: async () => ({language: window.language ?? 'en', hotkeyApps: 'cmd+shift+space', hotkeyLinks: 'cmd+option+space', secondaryBrowser: window.browser ?? '', scanApplications: true, discoverEdgeApps: true, iconServices: ['site'], allowPrivateIconHosts: false}),
    // Named libraryStatus, not status: window.status is a native Window
    // property (the old status-bar text) that stringifies anything
    // assigned to it, so a test object set there would never arrive.
    LibraryStatus: async () => (window.libraryStatus ?? {path: '/Users/someone/Library/Application Support/hopto/library.toml', error: '', line: 0, readOnly: false}),
    Launch: call('Launch'),
    OpenLink: call('OpenLink'),
    OpenLinkWith: call('OpenLinkWith'),
    CopyTarget: call('CopyTarget'),
    RevealInFinder: call('RevealInFinder'),
    RevealLibrary: call('RevealLibrary'),
    EditLibrary: call('EditLibrary'),
    Hide: call('Hide'),
    TabChanged: call('TabChanged'),
    Debug: call('Debug'),
    ToggleFavorite: async (key) => {
        window.calls.push(`ToggleFavorite:${key}`);
        const index = window.favs.indexOf(key);
        if (index >= 0) {
            window.favs.splice(index, 1);
            return false;
        }
        window.favs.push(key);
        return true;
    },
}}};

window.addEventListener('error', (event) => {
    window.calls.push(`ERROR:${event.message}`);
});
