// A stand-in for the Wails bridge, so the built page can be opened in a
// normal browser: every Go method the page calls is a promise here, and
// every call is appended to window.calls for the test to read. `emit`
// stands in for the `shown` event ("window.emit('links')").
window.calls = [];
window.favs = [];

// The runtime module generated by Wails implements EventsOn on top of
// EventsOnMultiple, so that is the one the page ends up calling. Both are
// provided so the bridge keeps working whichever the page uses. The last
// listener of each event is kept, so a test can fire `icons` too.
window.listeners = {};
window.runtime = {
    EventsOnMultiple: (name, callback) => {
        window.listeners[name] = callback;
        if (name === 'shown') {
            window.emit = callback;
        }
    },
    EventsOn: (name, callback) => {
        window.runtime.EventsOnMultiple(name, callback);
    },
};

// The fixture: two discovered apps (one an Edge app on github.com), one
// hand-added app, and one app of /System/Applications, search only.
const apps = [
    {id: 'mine', key: 'apps:mine', kind: 'app', source: 'library', name: 'Mine', description: 'A hand-added app', url: '', host: '', path: '/Applications/Mine.app', bundleId: '', category: 'tools', keywords: [], iconUrl: '', hidden: false, missing: false},
    {id: 'app-mail', key: 'apps:app-mail', kind: 'app', source: 'applications', name: 'Mail', description: '', url: '', host: '', path: '/Applications/Mail.app', bundleId: 'com.apple.mail', category: 'applications', keywords: [], iconUrl: '', hidden: false, missing: false},
    {id: 'edge-github', key: 'apps:edge-github', kind: 'app', source: 'edge', name: 'GitHub', description: 'github.com', url: 'https://github.com/', host: 'github.com', path: '/Users/someone/Applications/Edge Apps.localized/GitHub.app', bundleId: '', category: 'edge', keywords: [], iconUrl: '', hidden: false, missing: false},
    {id: 'app-calculator', key: 'apps:app-calculator', kind: 'app', source: 'applications', name: 'Calculator', description: '', url: '', host: '', path: '/System/Applications/Calculator.app', bundleId: 'com.apple.calculator', category: 'applications', keywords: [], iconUrl: '', hidden: false, missing: false, searchOnly: true},
];

const links = [
    {id: 'mdn', key: 'links:mdn', kind: 'link', source: 'library', name: 'MDN', description: 'Web reference', url: 'https://developer.mozilla.org', host: 'developer.mozilla.org', path: '', bundleId: '', category: 'docs', keywords: [], iconUrl: '', hidden: false, missing: false},
    {id: 'gitea', key: 'links:gitea', kind: 'link', source: 'library', name: 'Gitea', description: 'Repos', url: 'https://repos.example.com', host: 'repos.example.com', path: '', bundleId: '', category: 'eco', keywords: ['git'], iconUrl: '', hidden: false, missing: false},
    {id: 'github', key: 'links:github', kind: 'link', source: 'library', name: 'GitHub', description: 'Pull requests', url: 'https://github.com', host: 'github.com', path: '', bundleId: '', category: 'eco', keywords: [], iconUrl: '', hidden: false, missing: false},
];

// The chips of each tab, as arrays the fake AddCategory can grow.
const linkCategories = [
    {id: 'eco', name: 'Ecosystem', tab: 'links', virtual: false},
    {id: 'docs', name: 'Docs', tab: 'links', virtual: false},
];

const appCategories = [
    {id: 'tools', name: 'Tools', tab: 'apps', virtual: false},
    {id: 'applications', name: '', tab: 'apps', virtual: true},
    {id: 'edge', name: '', tab: 'apps', virtual: true},
];

/**
 * The id Go would give a name, near enough for the fixture.
 * @param {string} name
 * @returns {string}
 */
const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'item';

/**
 * Hands out the answer a test queued in window.nextSave, once.
 * @returns {object|null}
 */
const queuedSave = () => {
    const answer = window.nextSave ?? null;
    window.nextSave = null;
    return answer;
};

const call = (name) => async (...args) => {
    window.calls.push([name, ...args].join(':'));
};

window.go = {main: {App: {
    Items: async (tab) => (tab === 'links' ? (window.noLinks ? [] : links) : apps),

    // Like Go, the hidden chip closes the apps row only while an app is
    // hidden.
    Categories: async (tab) => {
        if (tab === 'links') {
            return linkCategories;
        }
        const hidden = apps.some((app) => app.hidden) ? [{id: 'hidden', name: '', tab: 'apps', virtual: true}] : [];
        return [...appCategories, ...hidden];
    },
    Usage: async () => ({opens: {'links:gitea': 2}, lastOpened: {'links:gitea': '2026-09-26T10:00:00Z'}, favorites: window.favs}),
    About: async () => ({version: 'v0.3.0-test', commit: 'abc1234', builtAt: '2026-09-27', goVersion: 'go1.27.1', libraryPath: '/Users/someone/Library/Application Support/hopto/library.toml'}),
    Settings: async () => ({language: window.language ?? 'en', hotkeyApps: 'cmd+shift+space', hotkeyLinks: 'cmd+option+space', secondaryBrowser: window.browser ?? '', scanApplications: true, discoverEdgeApps: true, iconServices: ['site'], allowPrivateIconHosts: false}),
    // Named libraryStatus, not status: window.status is a native Window
    // property (the old status-bar text) that stringifies anything
    // assigned to it, so a test object set there would never arrive.
    LibraryStatus: async () => (window.libraryStatus ?? {path: '/Users/someone/Library/Application Support/hopto/library.toml', error: '', line: 0, readOnly: false}),
    Launch: call('Launch'),
    OpenLink: call('OpenLink'),
    OpenLinkWith: call('OpenLinkWith'),
    CopyTarget: call('CopyTarget'),
    RevealInFinder: call('RevealInFinder'),
    RevealLibrary: call('RevealLibrary'),
    EditLibrary: call('EditLibrary'),

    // The editor. InspectURL answers after window.inspectDelay ms with
    // window.inspectDraft, or with a plausible page; the saves record the
    // input as JSON and, unless window.nextSave says otherwise, store the
    // link so the refresh after the save lists it.
    InspectURL: async (url) => {
        window.calls.push(`InspectURL:${url}`);
        await new Promise((done) => setTimeout(done, window.inspectDelay ?? 0));
        return window.inspectDraft ?? {url, host: new URL(url).hostname, name: 'Example Domain', description: 'Illustrative', iconDataUrl: '', insecure: url.startsWith('http:'), duplicate: null, sameHost: []};
    },
    AddLink: async (input) => {
        window.calls.push(`AddLink:${JSON.stringify(input)}`);
        const queued = queuedSave();
        if (queued) {
            return queued;
        }
        const id = slug(input.name);
        links.push({id, key: `links:${id}`, kind: 'link', source: 'library', name: input.name, description: input.description, url: input.url, host: new URL(input.url).hostname, path: '', bundleId: '', category: input.category, keywords: input.keywords, iconUrl: '', hidden: false, missing: false});
        return {id, problems: {}, duplicate: null};
    },
    UpdateLink: async (id, input) => {
        window.calls.push(`UpdateLink:${id}:${JSON.stringify(input)}`);
        const queued = queuedSave();
        if (queued) {
            return queued;
        }
        const link = links.find((entry) => entry.id === id);
        Object.assign(link, {name: input.name, description: input.description, url: input.url, host: new URL(input.url).hostname, category: input.category, keywords: input.keywords});
        return {id, problems: {}, duplicate: null};
    },
    AddCategory: async (tab, name) => {
        window.calls.push(`AddCategory:${tab}:${name}`);
        const view = {id: slug(name), name, tab, virtual: false};
        (tab === 'links' ? linkCategories : appCategories).push(view);
        return view;
    },
    // The welcome: Welcome answers window.welcome (nothing due unless a
    // test sets it); DismissWelcome makes it not due, as Go does.
    Welcome: async () => window.welcome ?? {show: false, firstRun: false, hotkeys: [], finderConflict: false},
    PresentWelcome: call('PresentWelcome'),
    DismissWelcome: async () => {
        window.calls.push('DismissWelcome');
        window.welcome = {...window.welcome, show: false};
    },
    OpenKeyboardSettings: call('OpenKeyboardSettings'),

    // Deleting, hiding and the chips. DeleteCategory refuses a chip that
    // still has items, with Go's own message.
    DeleteLink: async (id) => {
        window.calls.push(`DeleteLink:${id}`);
        links.splice(links.findIndex((link) => link.id === id), 1);
    },
    DeleteApp: async (id) => {
        window.calls.push(`DeleteApp:${id}`);
        apps.splice(apps.findIndex((app) => app.id === id), 1);
    },
    HideApp: async (id) => {
        window.calls.push(`HideApp:${id}`);
        apps.find((app) => app.id === id).hidden = true;
    },
    UnhideApp: async (id) => {
        window.calls.push(`UnhideApp:${id}`);
        apps.find((app) => app.id === id).hidden = false;
    },
    RenameCategory: async (tab, id, name) => {
        window.calls.push(`RenameCategory:${tab}:${id}:${name}`);
        (tab === 'links' ? linkCategories : appCategories).find((category) => category.id === id).name = name;
    },
    DeleteCategory: async (tab, id) => {
        window.calls.push(`DeleteCategory:${tab}:${id}`);
        if ([...links, ...apps].some((item) => item.category === id)) {
            throw new Error(`the category still has items: ${id}`);
        }
        const list = tab === 'links' ? linkCategories : appCategories;
        list.splice(list.findIndex((category) => category.id === id), 1);
    },

    // The apps editor. PickApp answers window.nextPick after
    // window.pickDelay ms (a cancel is {path: ''}), else a plausible
    // bundle; the saves store the app as Go would.
    PickApp: async () => {
        window.calls.push('PickApp');
        await new Promise((done) => setTimeout(done, window.pickDelay ?? 0));
        return window.nextPick ?? {path: '/Applications/Example.app', bundleId: 'org.example.app', name: 'Example', description: '', iconDataUrl: '', problem: '', duplicate: null};
    },
    AddApp: async (input) => {
        window.calls.push(`AddApp:${JSON.stringify(input)}`);
        const queued = queuedSave();
        if (queued) {
            return queued;
        }
        const id = slug(input.name);
        apps.push({id, key: `apps:${id}`, kind: 'app', source: 'library', name: input.name, description: input.description, url: '', host: '', path: input.path, bundleId: input.bundleId, category: input.category, keywords: [], iconUrl: '', hidden: false, missing: false});
        return {id, problems: {}, duplicate: null};
    },
    UpdateApp: async (id, input) => {
        window.calls.push(`UpdateApp:${id}:${JSON.stringify(input)}`);
        const queued = queuedSave();
        if (queued) {
            return queued;
        }
        Object.assign(apps.find((app) => app.id === id), {name: input.name, description: input.description, path: input.path, bundleId: input.bundleId, category: input.category});
        return {id, problems: {}, duplicate: null};
    },
    Hide: call('Hide'),
    TabChanged: call('TabChanged'),
    Debug: call('Debug'),
    ToggleFavorite: async (key) => {
        window.calls.push(`ToggleFavorite:${key}`);
        const index = window.favs.indexOf(key);
        if (index >= 0) {
            window.favs.splice(index, 1);
            return false;
        }
        window.favs.push(key);
        return true;
    },
}}};

window.addEventListener('error', (event) => {
    window.calls.push(`ERROR:${event.message}`);
});
